dist: focal
osx_image: xcode12.2

os:
    - linux
    - osx

addons:
    apt:
        packages:
            - libhyperscan-dev
            - libpcap-dev
            - tree
    homebrew:
        packages:
            - pkg-config
            - hyperscan
            - libpcap
            - tree

env:
    global:
        - GO111MODULE=on
        - PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/

language: go

go:
    - 1.14.x
    - 1.15.x
    - 1.16.x
    - 1.17.x
    - master

after_failure:
    - echo `pwd`
    - tree -h
